name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - git checkout main
      - pip3 install python
      - pip install -r requirements.txt
      - pytest tests/test_calculator.py -v  